### ISSUE TITLE
Simple things should easy

### ISSUE THREAD

**Issue by amdasilva** [GEOS-ESM/mepo#176]
The current instructions for cloning and getting ready to build is unecessarily complicated:

mepo clone git@github.com:GEOS-ESM/AeroApps
cd AeroApps
source env@/g5_modules
mkdir build
cd build
cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=ifort \
         -DCMAKE_INSTALL_PREFIX=../install
make -j6 install

Way too many steps. Can we just do this:

mepo --cmake clone git@github.com:GEOS-ESM/AeroApps
cd AeroApps/build; make -j6 install

Where the option --cmake just implements this:

cd AeroApps
source env@/g5_modules
mkdir build
cd build
cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=ifort \
         -DCMAKE_INSTALL_PREFIX=../install

The options above could be encoded in g5_modules or any other yaml file of your choice. Just get it out of the way.

Now, 'complicated things should be possible'.  You can omit the "--cmake" option and exercise all the cmake options.

**Comment by tclune** [comment]
There are several issues with the specifics of this request, but certainly something simpler can/should be enabled.

First, mepo is a wrapper for Git and should not (will not) be extended to become more aware of cmake and building in general.   Second, there are problems with moving the sourcing of `g5_modules` inside of mepo which is python based. (Possibly not impossible, but there are some issues in that direction.)

The way we handle this with GCM is to hide things inside of `parallel_build.csh` which can even handle the mepo aspects if someone did a raw git clone instead of a mepo clone.    Currently paralle_build.csh needs to be installed in each fixture, and is probably not quite suitable for aeroapps.  Possibly it could be generalized or something very similar could just be created.

Another approach is to create yet another layer that wraps mepo, cmake, and make steps.       But it would likely end up needing to support the union of the options across those 3 layers.

**Comment by mathomp4** [comment]
Building on what @tclune said, right now `parallel_build.csh` is essentially a "thin wrapper" with most of the bulk of the script in `ESMA_env/build.csh`. 

What `parallel_build.csh` does is:
1. Looks if `ESMA_env` is present, if not, run `mepo clone`
2. Then run `ESMA_env/build.csh`

`build.csh` is the one that does the fun stuff:
1. source g5_modules
2. run cmake (in various ways depending on command line options)
3. run `make -jN install` (either interactively or in a SLURM/PBS job). 

Essentially what the script did in the old GEOSgcm/adas days.

Now, something in pure cmake could look like this (using MAPL):
```
mepo clone git@github.com:GEOS-ESM/MAPL.git
cd MAPL
source ESMA_env/g5_modules.sh
cmake -S . -B build -DBASEDIR=$BASEDIR/Linux
cmake --build build --target install -jN
```
I am looking at seeing if we can avoid the `-DBASEDIR` bits

**Comment by tclune** [comment]
cmake can access BASEDIR as an env variable.     We could have it check the env variable if the command line has not defined it.

**Comment by pchakraborty** [comment]
Can this be closed?

**Comment by mathomp4** [comment]
I think so. I'll close it
